### ISSUE TITLE
Request on Knowledge graph README 

### ISSUE THREAD

**Issue by HwiyeolJo** [ihaeyong/drama-graph#10]
Describe the format of input in more details.
- How can we input a question into this system as you show in example

Need for explanations on the output formats.
- what do the frame.gv / triple.gv mean?
- Also, each label (e.g., Entity, Topical_entity) represents what?

Minor: Add commands to install stanfordnlpcore.

**Comment by fairy-of-9** [comment]
이슈 확인하였습니다.

comment로 답변을 우선하고 README를 수정할 예정입니다.

`How can we input a question into this system as you show in example`
- 해당 시스템은 대본을 입력으로 하여 지식그래프를 추출해냅니다. question을 입력으로 하지않습니다.  입력은 dramaQA에서 제공하는 대본데이터와 시간정보입니다. 입력/출력에 대한 파일을 업로드하여 공유할 예정입니다.

```
what do the frame.gv / triple.gv mean?
Also, each label (e.g., Entity, Topical_entity) represents what?
```
- 모듈은 추출된 내용을 `graph.json`로 출력을 합니다. 해당 json파일의 시각화를 위하여 graphviz 툴을 사용하는데, 해당 툴을 사용할 때 `*.gv` 파일이 생성됩니다. 출력된 그래프의 결과는 `graph.json`을 보시면 됩니다.

현재 입력(대본 및 시간정보)/출력(json 파일)에 대해 정리중에 있으며 정리 후에 공유할 예정입니다.

감사합니다.

**Comment by HwiyeolJo** [comment]
현재 README를 그대로 따라 run_knowledge_graph.sh 를 실행했을 경우,
graph.json 에 아무런 정보가 생성되지 않습니다.

**Comment by fairy-of-9** [comment]
README와 코드 일부분을 수정했습니다.
`git pull` 이후 수정된 README를 따라 실행해보시면 되겠습니다.

감사합니다.

**Comment by HwiyeolJo** [comment]
코드 실행 중 다음과 같은 에러가 납니다.

```
building graph..
 struct knowledge..
 done..
 make graph..
 done..
 visualizing..
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/graphviz/backend.py", line 129, in render
    subprocess.check_call(args, stderr=stderr, **POPEN_KWARGS)
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 44, in <module>
    graph_maker = graph_maker(config, extractor.output, back_KB.output)
  File "/drama-graph/knowledge_graph/graph_maker/graph_maker.py", line 44, in __init__
    self.visualization()
  File "/drama-graph/knowledge_graph/graph_maker/graph_maker.py", line 367, in visualization
    dot_triple.render(os.path.join(self.config['graph']['graph_path'], '{}_triple.gv'.format(qid)), view=False)
  File "/usr/local/lib/python3.6/dist-packages/graphviz/files.py", line 176, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/usr/local/lib/python3.6/dist-packages/graphviz/backend.py", line 132, in render
    raise ExecutableNotFound(args)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'data/output/graphs/ep1_scene-10_triple.gv'], make sure the Graphviz executables are on your systems' PATH
```

아마 아직 drama-graph 모듈이 완전하지 않아서 발생한 문제로 보이긴 합니다.

반면 graph.json 은 생성되는 것이 확인되어 결과를 살펴 보았으나,
아직 EP1에 대해서만 결과물이 나오는 것을 확인했습니다.
다른 EP에 대해서는 언제 결과물을 받아볼 수 있을까요?

먼저, EP1 결과물은 1세부 연구실들에게 샘플로 전달하겠습니다.

**Comment by fairy-of-9** [comment]
나머지 EP의 input/output을 정리하여 11월 첫째주까지 보내드리도록 하겠습니다.
에러는 패키지 경로로 인해 발생한 것 같습니다. 수정하는대로 push할 예정입니다.

감사합니다.

**Comment by fairy-of-9** [comment]
@HwiyeolJo 

안녕하세요.
나머지 EP에  대한 input/output을 [이 곳](https://drive.google.com/drive/folders/1IhWn82lBD96vTj6nvjdsCQOdQabi255L)에 정리해두었습니다.

감사합니다.
